Custom level
GameDevStudioUCSD/Shadowlight pull request #47
Opened 2018-03-25 05:57 UTC by ejoun6718

Here are the list of things I did:
-Added a new castle level, which is in the CastleLevel scene.
-Added the boolean "invincible" to the shadow player to make testing levels easier.
-Added ComboInput and ComboUnlockable scripts
-Removed excess unityevents in editor from the Button prefab

2018-03-27 21:34 UTC, sru requested changes
I haven't really looked at the level yet, just codes.

2018-03-27 21:34 UTC, sru commented on Assets/Scripts/ComboInput.cs
> +﻿using System.Collections; using System.Collections.Generic; using UnityEngine;  /**  * Works with the ComboUnlockable script to allow "unlockable" objects to  * perform an action as a result of the
Something's wrong with this file. Looks like there is no new lines. Can you fix it?

2018-03-27 21:34 UTC, sru commented on Assets/Scripts/ComboUnlockable.cs
> +﻿using System.Collections; using System.Collections.Generic; using UnityEngine; using UnityEngine.Events;  /** * Works with the ComboInput script to allow "unlockable" objects to * perform an action
Same as `ComboInput.cs`. Add new lines.

2018-03-27 21:34 UTC, sru commented on Assets/Scripts/PlayerController.cs
> +    public bool invincible = false;
Better way would be separating out the dying mechanism to another component. That way, we can just disable or enable those components containing dying mechanism to debug and test.

2018-03-27 21:34 UTC, sru commented on Assets/Scripts/Rideable.cs
> +public class Rideable : MonoBehaviour {
What does this do? What is it for?

2018-03-28 04:22 UTC, erikajoun commented on Assets/Scripts/ComboInput.cs
> +﻿using System.Collections; using System.Collections.Generic; using UnityEngine;  /**  * Works with the ComboUnlockable script to allow "unlockable" objects to  * perform an action as a result of the
That is very weird... I have just fixed both of the scripts.

2018-03-28 11:52 UTC, sru commented
I just played the level with my brother. We concluded that the puzzle itself was fine, but the platforms were so close together that we found it difficult to determine which ones we can jump over and which ones we cannot jump over. I felt that the characters should be able to jump over all the platforms, but no, I can't really jump onto any platforms without help of the boxes.

2018-03-28 11:56 UTC, sru commented
Oh, and remove `Assets/Sprites/Objects/GrowingPlant.meta`. The branch does not have anything committed named `Assets/Sprites/Objects/GrowingPlant`, but the meta file is still committed. You should remove it (or, not include it in the commits).

2018-04-15 01:09 UTC, merged